// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateSession(arg1) {
  return window['go']['main']['App']['ActivateSession'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function ChooseWorkspace() {
  return window['go']['main']['App']['ChooseWorkspace']();
}

export function ClearPeerMessages() {
  return window['go']['main']['App']['ClearPeerMessages']();
}

export function CommitWorktree(arg1, arg2) {
  return window['go']['main']['App']['CommitWorktree'](arg1, arg2);
}

export function ConfirmClearPeerMessages() {
  return window['go']['main']['App']['ConfirmClearPeerMessages']();
}

export function ConfirmDiscardFileChanges() {
  return window['go']['main']['App']['ConfirmDiscardFileChanges']();
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateWorkspaceSession(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceSession'](arg1, arg2);
}

export function CreateWorktreeBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateWorktreeBranch'](arg1, arg2);
}

export function CreateWorktreeSession(arg1, arg2) {
  return window['go']['main']['App']['CreateWorktreeSession'](arg1, arg2);
}

export function DeletePeerMessage(arg1) {
  return window['go']['main']['App']['DeletePeerMessage'](arg1);
}

export function EnsureWorktreeShellSession(arg1) {
  return window['go']['main']['App']['EnsureWorktreeShellSession'](arg1);
}

export function GetCommitRangeDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitRangeDiff'](arg1, arg2, arg3);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetWorktreeCommitHistory(arg1, arg2) {
  return window['go']['main']['App']['GetWorktreeCommitHistory'](arg1, arg2);
}

export function GetWorktreeDiff(arg1) {
  return window['go']['main']['App']['GetWorktreeDiff'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListWorktreeEntries(arg1, arg2) {
  return window['go']['main']['App']['ListWorktreeEntries'](arg1, arg2);
}

export function ListWorktreeFiles(arg1) {
  return window['go']['main']['App']['ListWorktreeFiles'](arg1);
}

export function PushWorktree(arg1) {
  return window['go']['main']['App']['PushWorktree'](arg1);
}

export function ReadWorktreeFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorktreeFile'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SaveUIState(arg1) {
  return window['go']['main']['App']['SaveUIState'](arg1);
}

export function SaveWorktreeFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWorktreeFile'](arg1, arg2, arg3, arg4);
}

export function SearchWorktreeContents(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWorktreeContents'](arg1, arg2, arg3);
}

export function SendSessionInput(arg1, arg2) {
  return window['go']['main']['App']['SendSessionInput'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StageWorktreeAll(arg1) {
  return window['go']['main']['App']['StageWorktreeAll'](arg1);
}

export function UpdateSessionCWD(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionCWD'](arg1, arg2);
}

export function UpdateSessionMode(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionMode'](arg1, arg2);
}
